baseURL = 'https://wiki.timothylim.is/'
languageCode = 'en-us'
title = "Tim's wiki"
theme = 'hugo-book'

[params]
  # Add this line to use the custom home layout
  customLayout = ["home"]
  # Add this line to disable the favicon
  favicon = false
